name: Build LaTeX document
on: push

env:
  dir: paper
jobs:
  build_latex:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Update the system
        run: sudo apt-get update

      - name: Install latexmk
        run: sudo apt-get install texlive-full

      - name: Compile
        run: make -C written && make -C written book

      - name: Zip pdf
        run: zip archive.zip written/main.pdf written/book.pdf

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive.zip
          path: ${{ env.dir}}/archive.zip

  release_pdf:
    name: Release PDF
    needs: build_latex
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: archive.zip

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          artifacts: archive.zip
          tag: paper-${{ steps.vars.outputs.sha_short }}
